# Generated by Django 3.2.12 on 2022-03-31 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('f04a68e6-3d6c-4900-9748-05091b2075a3'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=128, null=True)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('f04a68e6-3d6c-4900-9748-05091b2075a3'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_liked', models.BooleanField(default=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='posts.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
