# Generated by Django 3.2.12 on 2022-03-31 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9ac35932-4bd9-4c18-8e66-83c179eb9ada'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9ac35932-4bd9-4c18-8e66-83c179eb9ada'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
