# Generated by Django 3.2.12 on 2022-03-31 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220401_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(1, 'Odin'), (2, 'Dva'), (3, 'Tri')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6560a08-c2f3-4573-bc1d-b6e2268e1e91'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6560a08-c2f3-4573-bc1d-b6e2268e1e91'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
