# Generated by Django 3.2.12 on 2022-03-31 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220401_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a0ed7d26-00aa-43aa-8cf0-f79d979225ad'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(1, 'Odin'), (2, 'Dva'), (3, 'Tri')], default=1, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a0ed7d26-00aa-43aa-8cf0-f79d979225ad'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
