# Generated by Django 3.2.12 on 2022-03-31 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220401_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d1b91913-6b42-4e42-a905-bfe52be29d26'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(1, 'Odin'), (2, 'Dva'), (3, 'Tri')], default=1, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d1b91913-6b42-4e42-a905-bfe52be29d26'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
