# Generated by Django 3.2.12 on 2022-03-31 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220401_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('abc61ea9-2e75-4f87-9382-df6f61764c63'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('abc61ea9-2e75-4f87-9382-df6f61764c63'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
