# Generated by Django 3.2.12 on 2022-03-31 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('743660d6-fac0-4542-819a-2f7600c11d68'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
