# Generated by Django 3.2.12 on 2022-03-31 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8b6aeb5d-e19b-4a28-be9f-b1ca612e1bd7'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
