# Generated by Django 3.2.12 on 2022-03-31 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cfeaad6f-d961-4c10-8221-7ea110220ae6'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
