# Generated by Django 3.2.12 on 2022-03-31 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('17468d62-66c0-43cf-b520-01168e773a83'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
