# Generated by Django 3.2.12 on 2022-03-31 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('daad635b-ad14-470e-8198-b7eef01c4dd9'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
