# Generated by Django 3.2.12 on 2022-03-31 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a0ed7d26-00aa-43aa-8cf0-f79d979225ad'), editable=False, primary_key=True, serialize=False, verbose_name='Уникальное поле'),
        ),
    ]
